[package]
name = "netapp"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
netapp-common = { path = "../netapp-common", features = ["user"] }
aya = { workspace = true, default-features = true }
anyhow = { workspace = true, default-features = true }
clap = { workspace = true }
env_logger = { workspace = true, default-features = true }
libc = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "signal", "sync", "time"] }
ratatui = "0.30"
crossterm = { version = "0.29", features = ["event-stream"] }

[build-dependencies]
aya-build = { workspace = true, default-features = true }
anyhow = { workspace = true, default-features = true }

[[bin]]
name = "netapp"
path = "src/main.rs"
